//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalmartManagementApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrator
    {
        public string username { get; set; }
        public string password { get; set; }
        public string fullname { get; set; }
        public string gender { get; set; }
        public string emailid { get; set; }
        public string usertype { get; set; }
    }
}
