//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalmartManagementApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bill()
        {
            this.billdetails = new HashSet<billdetail>();
        }
    
        public int billid { get; set; }
        public Nullable<int> cardnumber { get; set; }
        public Nullable<int> storeid { get; set; }
        public Nullable<int> empid { get; set; }
        public decimal totalamount { get; set; }
        public decimal discount { get; set; }
        public decimal billamount { get; set; }
        public string dateofbill { get; set; }
    
        public virtual membership_cards membership_cards { get; set; }
        public virtual storeemployee storeemployee { get; set; }
        public virtual store store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<billdetail> billdetails { get; set; }
    }
}
