//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalmartManagementApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class billdetail
    {
        public int bdid { get; set; }
        public Nullable<int> billid { get; set; }
        public Nullable<int> productid { get; set; }
        public decimal quantity { get; set; }
        public decimal price { get; set; }
        public decimal discount { get; set; }
        public decimal netprice { get; set; }
        public decimal totalamount { get; set; }
    
        public virtual bill bill { get; set; }
        public virtual product product { get; set; }
    }
}
