//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalmartManagementApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class membership
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public membership()
        {
            this.membership_cards = new HashSet<membership_cards>();
        }
    
        public int memberid { get; set; }
        public string merchantname { get; set; }
        public string emailid { get; set; }
        public string mobileno { get; set; }
        public string address { get; set; }
        public string identifyproof { get; set; }
        public string vatno { get; set; }
        public string servicetaxno { get; set; }
        public string dateofexpiry { get; set; }
        public string status { get; set; }
        public Nullable<int> storeid { get; set; }
    
        public virtual store store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<membership_cards> membership_cards { get; set; }
    }
}
