//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalmartManagementApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class membership_cards
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public membership_cards()
        {
            this.bills = new HashSet<bill>();
            this.feedbacks = new HashSet<feedback>();
        }
    
        public int cardnumber { get; set; }
        public string cardholdernname { get; set; }
        public string photo { get; set; }
        public string Mobileno { get; set; }
        public string address { get; set; }
        public Nullable<int> memberid { get; set; }
    
        public virtual membership membership { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bill> bills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<feedback> feedbacks { get; set; }
    }
}
