//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalmartManagementApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.stocks = new HashSet<stock>();
            this.billdetails = new HashSet<billdetail>();
        }
    
        public int pid { get; set; }
        public string productname { get; set; }
        public string description { get; set; }
        public Nullable<int> subcatid { get; set; }
        public decimal price { get; set; }
        public Nullable<decimal> discount { get; set; }
        public string photo { get; set; }
        public Nullable<int> storeid { get; set; }
        public string skunumber { get; set; }
    
        public virtual store store { get; set; }
        public virtual subcategory subcategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stock> stocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<billdetail> billdetails { get; set; }
    }
}
