//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalmartManagementApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock
    {
        public int stockid { get; set; }
        public Nullable<int> productid { get; set; }
        public Nullable<int> storeid { get; set; }
        public int quantity { get; set; }
        public string dateofstock { get; set; }
        public Nullable<int> employeeid { get; set; }
    
        public virtual product product { get; set; }
        public virtual storeemployee storeemployee { get; set; }
        public virtual store store { get; set; }
    }
}
