//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalmartManagementApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WalmartContext : DbContext
    {
        public WalmartContext()
            : base("name=WalmartContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrator> Administrators { get; set; }
        public virtual DbSet<store> stores { get; set; }
        public virtual DbSet<storeemployee> storeemployees { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<subcategory> subcategories { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<membership> memberships { get; set; }
        public virtual DbSet<membership_cards> membership_cards { get; set; }
        public virtual DbSet<stock> stocks { get; set; }
        public virtual DbSet<bill> bills { get; set; }
        public virtual DbSet<billdetail> billdetails { get; set; }
        public virtual DbSet<feedback> feedbacks { get; set; }
    }
}
